# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba0bf995373d28147aab8947f60cb531e4d4f5dbf8119fbb0140534fd6fd749372ce2861b928feb160e3e82388a23358705354b9f86af9193a59dcc1abeab7bc

test:
  secret_key_base: 9f5cd24cb7d3f1ac09c28c3a67a1ea091be0c75f2c3cca138639b817e2bd1c47303b1a2e87b1523f827f499524abfbb301f99c4203b35e4f78fc26c3177e23f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
